---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here

    - name: "install python for Ansible."
      # Your code here
      sudo apt update
      sudo apt install python3-pip

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"  
    - AWS_ACCESS_KEY_ID: AKIAZCS4ECRVINJ6KNKP
    - AWS_DEFAULT_REGION:	us-east-01
    - AWS_SECRET_ACCESS_KEY: r7AUSBIHZRtJTTX5sODVLl2R+f/mtB1uWh7QtucZ
    # Add more env vars here

  roles:
    # Your code here