---
- name: "upgrade packages & install dependencies"
  command: |
    apt update
    apt install nodejs
    apt install npm

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
