---
- name: Copy artifact into the EC2 instance
  copy:
    src: ./artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "extract the zipped artifact into the EC2 instance."
  command: |
      cd backend
      tar -xvzf ../artifact.tar.gz

- name: "start the app."
  command: |
    npm install
    pm2 stop default
    pm2 start npm -- start