---
- name: Copy artifact into the EC2 instance
  copy:
    src: ./artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: "extract the zipped artifact into the EC2 instance."
  command: |
  tar -xvjf artifact.tar.gz -C 

- name: "start the app."
  command: |
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start